# Generated by Django 5.2.2 on 2025-06-09 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_cell', models.CharField(max_length=100, unique=True)),
                ('lineType', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Cells',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('cells', models.ManyToManyField(related_name='items', to='system.cells')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_items', to='system.items')),
            ],
            options={
                'verbose_name_plural': 'Work Order Items',
            },
        ),
        migrations.CreateModel(
            name='Scans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('scanned_items', models.PositiveIntegerField(default=1)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='system.items')),
                ('workOrderItems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='system.workorderitems')),
            ],
            options={
                'verbose_name_plural': 'Scans',
            },
        ),
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('closedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work Orders',
            },
        ),
        migrations.AddField(
            model_name='workorderitems',
            name='workorders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_items', to='system.workorders'),
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(choices=[('exceeded_limit', 'Excedió el límite de piezas en esta celda'), ('missing_parts', 'Faltan piezas en esta celda'), ('already_entered', 'Esta pieza ya fue ingresada'), ('wrong_work_order', 'Esta pieza no pertenece a esta orden de trabajo'), ('wrong_cell', 'Esta pieza no debería estar aún en esta celda')], max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='system.items')),
                ('workorders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='system.workorders')),
            ],
            options={
                'verbose_name_plural': 'Errors',
            },
        ),
    ]
