# Generated by Django 5.2 on 2025-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitems',
            name='cells',
            field=models.ManyToManyField(related_name='workOrderItems', to='system.cells'),
        ),
    ]
