# Generated by Django 5.2.2 on 2025-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_workorderitems_cells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderitems',
            name='cells',
        ),
        migrations.AddField(
            model_name='workorders',
            name='cells',
            field=models.ManyToManyField(related_name='workOrderItems', to='system.cells'),
        ),
        migrations.AlterField(
            model_name='cells',
            name='lineType',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('varnish', 'Varnish'), ('polish', 'Polish'), ('paint', 'Paint')], max_length=10),
        ),
    ]
