# Generated by Django 5.2 on 2025-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_workorderitems_cells_workorders_cells_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitems',
            name='serialized_part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cells',
            name='lineType',
            field=models.CharField(choices=[('ensamble', 'Ensamble'), ('pintura', 'Pintura'), ('empaque', 'Empaque')], max_length=10),
        ),
    ]
